id: A37890190
base_file: f600F.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - bo
  datatype: PlainText
  created_at: 2022-05-30 22:03:24.110187
  last_modified_at: 2022-05-30 22:03:24.110194
